name: "ðŸ› Bug Report"
description: "Report a bug or unexpected behavior. Include steps to reproduce."
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report

        Please provide detailed information to help us reproduce and fix the issue.

        **Before submitting**, please:
        - Search existing issues to avoid duplicates
        - Test with the latest version if possible
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight Checklist
      description: Please confirm the following.
      options:
        - label: I have searched existing issues and this is not a duplicate
          required: true
        - label: I have tested with the latest version (if applicable)
          required: false
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: What actually happens? Be specific.
      placeholder: |
        When I click the submit button, the form shows a spinner indefinitely
        and eventually times out with a generic error message.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: |
        The form should submit successfully and redirect to the confirmation page,
        or show a specific error message if validation fails.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the bug.
      placeholder: |
        1. Go to '/settings/profile'
        2. Change the email field to 'test@example.com'
        3. Click 'Save Changes'
        4. Observe the infinite spinner
      render: markdown
    validations:
      required: true
  - type: dropdown
    id: frequency
    attributes:
      label: Bug Frequency
      description: How often does this occur?
      options:
        - "Always (100% reproducible)"
        - "Often (>50% of the time)"
        - "Sometimes (<50% of the time)"
        - "Rarely (hard to reproduce)"
        - "Once (happened only once)"
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: What is the impact of this bug?
      options:
        - "Critical - System down, data loss, security issue"
        - "High - Major feature broken, no workaround"
        - "Medium - Feature impaired, workaround exists"
        - "Low - Minor inconvenience, cosmetic issue"
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment.
      placeholder: |
        - OS: macOS 14.0 / Windows 11 / Ubuntu 22.04
        - Browser: Chrome 120 / Firefox 121 / Safari 17
        - Device: Desktop / Mobile (iPhone 15)
        - App Version: v1.2.3
        - Node Version: 20.x (if applicable)
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Error Messages
      description: Paste any error messages, console logs, or stack traces.
      placeholder: |
        Error: NetworkError when attempting to fetch resource.
        at fetchData (src/api/client.js:42)
        at handleSubmit (src/components/Form.js:28)
      render: shell
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Videos
      description: Attach any visual evidence (drag and drop images here).
      placeholder: |
        Drag and drop screenshots or screen recordings here.
    validations:
      required: false
  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Have you found a temporary workaround?
      placeholder: |
        Refreshing the page and trying again sometimes works.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information.
      placeholder: |
        - This started happening after the v1.2.0 release
        - Related to #789
        - Possibly related to recent auth changes
    validations:
      required: false
